session_name: prode-dev
shell_command_before: workon prode
windows:
  - window_name: bash
    focus: true
    panes:
      -export DJANGO_READ_DOT_ENV_FILE True
  - window_name: nvim
    panes:
      -nvim
  - window_name: dev-server
    panes:
      -make node
      -make dev
