# Generated by Django 2.0.5 on 2018-05-16 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganador', models.CharField(choices=[('E', 'Empate'), ('L', 'Gana {local}'), ('V', 'Gana {visitante}')], default='E', max_length=1)),
                ('goles_local', models.PositiveSmallIntegerField(default=0)),
                ('goles_visitante', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('vencimiento', models.DateTimeField()),
                ('slug', models.SlugField()),
                ('publica', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', django_countries.fields.CountryField(max_length=2)),
                ('visitante', django_countries.fields.CountryField(max_length=2)),
                ('goles_local', models.PositiveSmallIntegerField(null=True)),
                ('goles_visitante', models.PositiveSmallIntegerField(null=True)),
                ('etapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='apuestas.Etapa')),
            ],
        ),
        migrations.AddField(
            model_name='apuesta',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to='apuestas.Partido'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
