# Generated by Django 2.0.5 on 2018-05-16 23:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apuestas', '0002_auto_20180516_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apuesta',
            unique_together={('usuario', 'partido')},
        ),
    ]
