# Generated by Django 2.0.5 on 2018-05-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0003_auto_20180516_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuesta',
            name='ganador',
            field=models.CharField(choices=[('E', 'Empate'), ('L', 'Gana local'), ('V', 'Gana visitante')], default='E', max_length=1),
        ),
    ]
