# Generated by Django 2.0.5 on 2018-05-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0005_partido_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apuesta',
            options={'ordering': ('usuario__username',)},
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ('fecha',)},
        ),
        migrations.AlterField(
            model_name='etapa',
            name='nombre',
            field=models.CharField(help_text="Por ejemplo 'Fase de grupos'", max_length=255),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='publica',
            field=models.BooleanField(help_text='\n    Tildar cuando la etapa este lista para ser mostrada a los apostadores para\n    que empiecen a apostar'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='slug',
            field=models.SlugField(help_text="Texto que se mostrara en la url, por\n    ejemplo si el slug fuera 'fase-de-grupos' la URL sería\n    '/apuestas/etapas/fase-de-grupos/'"),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='vencimiento',
            field=models.DateTimeField(help_text='Fecha-hora hasta que será\n    permitido apostar. Idealmente debe ser antes que empiece el primer partido\n    de la etapa. [dd/mm/aaaa hh:mm]'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en la que se juega el partido\n        [dd/mm/aaaa hh:mm]', null=True),
        ),
    ]
