# Generated by Django 2.0.5 on 2018-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0006_auto_20180518_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='slug',
            field=models.SlugField(help_text="Texto que se mostrara en la url, por\n    ejemplo si el slug fuera 'fase-de-grupos' la URL sería\n    '/apuestas/etapas/fase-de-grupos/'", unique=True),
        ),
    ]
