# Generated by Django 2.0.5 on 2018-06-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0008_auto_20180521_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apuesta',
            options={'ordering': ('usuario__username', 'partido__fecha')},
        ),
        migrations.AlterModelOptions(
            name='etapa',
            options={'get_latest_by': 'created', 'ordering': ('created',)},
        ),
    ]
